name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: griffig.xyz/base
      credentials:
        username: ${{ secrets.DOCKER_REGISTRY_USER }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Configure and build
      run: |
        pip install .

    # - name: Build Python wheels
    #   uses: RalfG/python-wheels-manylinux-build@v0.3.3-manylinux2014_x86_64
    #   with:
    #     build-requirements: 'pybind11'
    #     system-packages: 'opencv opencv-devel eigen3'
