name: Upload Python Package

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine cibuildwheel --upgrade

    - name: Build manylinux wheels
      uses: RalfG/python-wheels-manylinux-build@v0.3.4
      with:
        python-versions: 'cp36-cp36m cp37-cp37m cp38-cp38 cp39-cp39'
        build-requirements: 'numpy'
        system-packages: 'cmake libglvnd-opengl mesa-libGL mesa-libGL-devel mesa-libGLU mesa-libGLU-devel mesa-libEGL mesa-libEGL-devel glew glew-devel'
        pre-build-command: 'sh .github/workflows/install-base.sh'

    # - name: Build wheels
    #   env:
    #     CIBW_BUILD: cp36-* cp37-* cp38-* cp39-*
    #   run: |
    #     python -m cibuildwheel --output-dir dist

    - name: Publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist
        twine upload dist/*
        twine upload wheelhouse/*-manylinux*.whl
